### ISSUE TITLE
关于组件在使用时代码补全和类型推导的问题

### ISSUE THREAD

**Issue by loclink** [yang1206/uniapp-nutui#12]
操作系统：macos13.5
开发工具：vscode version 1.81
uniapp版本：3.0.0
uniapp-nutui组件库版本：0.2.2

问题描述：使用vscode开发时，需要借助插件： `nutui-vscode-extension`，才能获得nutui每个组件的类型推导能力，但我使用monorepo结构组织项目时，偶然发现，如果在uniapp-nutui包中的开发时依赖中加入`@vue/runtime-core` ,就像这样：
``` json
{
"devDependencies": {
    "@vue/runtime-core": "^3.2.47"
  },
}
```
之后在我的项目中把 `tsconfig.json` 的`types`选项中加入 `"uniapp-nutui/global.d.ts"`，像这样：

``` json
 {
 "types": [
      "@dcloudio/types",
      "./components.d.ts",
      **"uniapp-nutui/global.d.ts",**
      "wm-uni-design/components.d.ts",
      "vite/client",
      "uni-app-types"
    ]
}
``` 
然后重新安装依赖并重新打开vscode，此时同样可以获得非常友好的提示：
![image](https://github.com/yang1206/uniapp-nutui/assets/106688231/701a4015-ea43-415e-bb5b-ff4e5e11c68b)

![image](https://github.com/yang1206/uniapp-nutui/assets/106688231/9296c2df-248e-4e53-bbc5-72dea1448915)

我了解这是volar在发挥作用。个人认为这是目前最好的获得uniapp组件类型推导的方式。

之后在项目中如果使用uniapp提供的easycom去自动加载依赖：

``` json
{
 "easycom": {
    "autoscan": true,
    "custom": {
      "^nut-(.*)?-(.*)": "uniapp-nutui/components/$1$2/$1$2.vue",
      "^nut-(.*)": "uniapp-nutui/components/$1/$1.vue",
    }
  }
}

```

甚至都不需要使用 `@uni-helper/vite-plugin-uni-components` 的 `resolvers` 中注册 `NutResolver()` ，这样插件自动产生的 `components.d.ts` 仅仅只会产生项目中自己的全局组件类型，而不会多余生成nutui相关的组件类型声明。

**Comment by yang1206** [comment]
其实不需要安装nutui-vscode-extension也可以获得类型提示，你需要显式安装@vue/runtime-core这是因为pnpm和volar额问题，具体可以看这个issue https://github.com/antfu/unplugin-vue-components/issues/355#issuecomment-1098939308
只需要在tsconfig里添加类型声明文件就可以了
