### ISSUE TITLE
飞书小程序-无法生成popup.js文件

### ISSUE THREAD

**Issue by Zane-Chen** [yang1206/uniapp-nutui#2]
通过HBuilderX导入的，无法在飞书小程序正常加载popup。相关截图如下：
![image](https://github.com/yang1206/uniapp-nutui/assets/105442272/1277da41-0590-49b0-8767-c72ee1825f81)
![image](https://github.com/yang1206/uniapp-nutui/assets/105442272/81e5db01-5ccc-48f0-a88e-3acbaf1ceec3)

**Comment by yang1206** [comment]
hbuilder使用 popup需要同时使用overlay 组件(我也不知道为什么)，什么属性都不用加，推荐使用 cli

**Comment by Zane-Chen** [comment]
好像确实如此，有个nut-popup的bug，源码中我没看到有接收position属性，导致位置有问题。即弹出位置设置无效。
![image](https://github.com/yang1206/uniapp-nutui/assets/105442272/333f6dbf-c424-4cf0-9cff-4e2f8aefb6ab)
![image](https://github.com/yang1206/uniapp-nutui/assets/105442272/f8932758-5c2d-45ba-8cf0-7ed1552890a1)

**Comment by yang1206** [comment]
<img width="378" alt="SCR-20230718-mfmg" src="https://github.com/yang1206/uniapp-nutui/assets/28709596/7c4f559e-14a9-4982-8a55-ca57c1210068">
<img width="561" alt="SCR-20230718-mfph" src="https://github.com/yang1206/uniapp-nutui/assets/28709596/826d3f01-fa24-4b59-b4ac-a97a51650ac6">

测试未发现问题，可能同样是 hbuilder编译的问题
