### ISSUE TITLE
微信小程序：样式失效

### ISSUE THREAD

**Issue by lizhijie429** [yang1206/uniapp-nutui#22]
从微信开发者工具中可以查看到样式已经按需导入，但是没有添加对应的class类名，导致样式失效。

![image](https://github.com/yang1206/uniapp-nutui/assets/7768535/6520cc80-cd41-468d-98b2-9e7f341ac3dc)

需手动添加class类名才能生效

![image](https://github.com/yang1206/uniapp-nutui/assets/7768535/5105988f-0208-4d2e-a48f-3e693754262f)

**Comment by lizhijie429** [comment]
使用 vite cli创建的工程，使用pnpm安装的uniapp-nutui包，node版本为18.16.0。

**Comment by lizhijie429** [comment]
可以看到导入的组件经过编译之后，已经不是原来的class类名了。
![image](https://github.com/yang1206/uniapp-nutui/assets/7768535/509a3a4c-1335-47ea-a031-f1fdc9c5c778)

**Comment by yang1206** [comment]
请提供复现工程

**Comment by lizhijie429** [comment]
#

> 请提供复现工程

https://github.com/lizhijie429/uni-app-untui.git

**Comment by lizhijie429** [comment]
> > 请提供复现工程
> 
> https://github.com/lizhijie429/uni-app-untui.git

下载之后直接安装依赖（node：18.16.0）

pnpm install

pnpm dev:mp-weixin

按照提示打开微信开发者工具预览即可发现问题。

**Comment by yang1206** [comment]
uniapp的 vite插件要放到最后
```
plugins: [
    Components({
      resolvers: [NutResolver()]
    }),
    uni()
  ],
```

**Comment by yang1206** [comment]
如果已解决请主动关闭 issue

**Comment by lizhijie429** [comment]
> 如果已解决请主动关闭 issue
问题已解决，希望该问题的注意事项补充在文档中。
