### ISSUE TITLE
这是啥问题啊[plugin:vite:css] [postcss] Failed to find 'uniapp-nutui/styles/index'

### ISSUE THREAD

**Issue by wca8** [yang1206/uniapp-nutui#23]
![image](https://github.com/yang1206/uniapp-nutui/assets/77438963/cd8134f2-5543-49ea-b37f-47919d0da0cc)

**Comment by yang1206** [comment]
请提供复现工程

**Comment by wca8** [comment]
解决了 style上忘记加 lang='scss'了

**Comment by wca8** [comment]
> 请提供复现工程

解决了 style上忘记加 lang='scss'了
