### ISSUE TITLE
看着按需导入成功 没有样式

### ISSUE THREAD

**Issue by wca8** [yang1206/uniapp-nutui#25]
![image](https://github.com/yang1206/uniapp-nutui/assets/77438963/510acd71-b866-4c78-bfd1-990855f0e9c7)

**Comment by lizhijie429** [comment]
跟我的问题一样的。 #22

**Comment by wca8** [comment]
> 跟我的问题一样的。 #22

你最后怎么解决的呀

**Comment by yang1206** [comment]
https://github.com/yang1206/uniapp-nutui/issues/22#issuecomment-1689595490
