### ISSUE TITLE
nut-address自定义地址显示问题

### ISSUE THREAD

**Issue by mingliangcheng** [yang1206/uniapp-nutui#26]
![image](https://github.com/yang1206/uniapp-nutui/assets/76807344/76910d80-a9ee-4f8f-b766-87a6fc5d3bef)
![image](https://github.com/yang1206/uniapp-nutui/assets/76807344/81b29edd-be00-4b8b-9d7e-d8ca98fcb98a)
address组件按照官网demo选择自定义地址，标题栏中会出现返回箭头，点击跳转到配送至页面，如图所示，而官方示例中没有。

**Comment by yang1206** [comment]
请提供复现工程

**Comment by mingliangcheng** [comment]
用法如图
![image](https://github.com/yang1206/uniapp-nutui/assets/76807344/3d83103c-3a6d-4b6c-8654-4c6f88829bb9)

**Comment by yang1206** [comment]
已有地址切换请参考https://www.uniapp-nutui.tech/components/business/address.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%9C%B0%E5%9D%80%E4%B8%8E%E5%B7%B2%E6%9C%89%E5%9C%B0%E5%9D%80%E5%88%87%E6%8D%A2
