### ISSUE TITLE
infinite-loading组件无法使用

### ISSUE THREAD

**Issue by leftScience** [yang1206/uniapp-nutui#27]
`
<template>
  <nut-infinite-loading v-model="infinityValue" load-txt="Loading..." load-more-txt="End~" :has-more="hasMore" @load-more="loadMore" :threshold="500">
    <div class="test" v-for="(item, index) in sum" :key="index">{{ index }}</div>
  </nut-infinite-loading>
</template>

<script setup>
  import { ref } from 'vue'
  const cycle = ref(0)
  const tabsValue = ref(0)
  const sum = ref(24)
  const infinityValue = ref(false)
  const hasMore = ref(true)
  const loadMore = (done) => {
    setTimeout(() => {
      sum.value = sum.value + 24
      cycle.value++
      if (cycle.value > 2) hasMore.value = false
      infinityValue.value = false
    }, 1000)
  }
</script>

<style>
  .test {
    padding: 12px 0 12px 20px;
    border-top: 1px solid #eee;
  }
</style>

`

无法触发  loadMore 事件

**Comment by yang1206** [comment]
这个组件并没有正式支持
