### ISSUE TITLE
地址组件使用问题

### ISSUE THREAD

**Issue by ZhongboHuang** [yang1206/uniapp-nutui#3]
1. 无法使用 v-model 设置默认选中值
![image](https://github.com/yang1206/uniapp-nutui/assets/55689028/b5b381b2-3f42-4d52-9a52-9103b2c0c3f9)
![image](https://github.com/yang1206/uniapp-nutui/assets/55689028/4420e2c9-5e9c-48d9-b074-78ab45e74ff4)
2. 使用 change 会触发两次 close 钩子函数

**Comment by ZhongboHuang** [comment]
若使用v-model:value, props.modelValue始终都是[]

**Comment by yang1206** [comment]
请提供一个最小重现
