### ISSUE TITLE
关于Icon组件不生效问题

### ISSUE THREAD

**Issue by Yer11214** [yang1206/uniapp-nutui#31]
### uniapp-nutui 版本号

0.2.4

### 平台

h5

### 重现链接

https://github.com/Yer11214/uniapp-nutui-findout-bug

### 重现步骤

在首页中无法查看Icon 直接运行就可以看到

### 期望的结果是什么？

根据文档描述 [icon](https://www.uniapp-nutui.tech/components/basic/icon.html) 里面写的一样但是icon不展示

### 实际的结果是什么？

展示icon

### 环境信息

  System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700
    Memory: 9.75 GB / 31.78 GB
  Binaries:
    Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.54)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    uniapp-nutui: ^0.2.4 => 0.2.4

**Comment by yang1206** [comment]
App.vue的 style不要加scoped，公共样式……
