### ISSUE TITLE
商品卡片vipPrice不填也会展示

### ISSUE THREAD

**Issue by Yer11214** [yang1206/uniapp-nutui#35]
### uniapp-nutui 版本号

0.2.5

### 平台

h5

### 重现链接

https://github.com/Yer11214/uniapp-nutui-findout-bug.git

### 重现步骤

npm run dev:h5 运行，首页中就可以看到 代码中没写vipPrice但是展示出了0元

### 期望的结果是什么？

不填不展示

### 实际的结果是什么？

不填不展示

### 环境信息

  System:
    OS: Windows 10 10.0.22621
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700
    Memory: 9.16 GB / 31.78 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.12 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.62)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    uniapp-nutui: ^0.2.4 => 0.2.4

**Comment by yang1206** [comment]
<img width="668" alt="image" src="https://github.com/yang1206/uniapp-nutui/assets/28709596/119bce22-a00a-475b-9f27-ee840bc683e9">
看文档

**Comment by yang1206** [comment]
0.3.1已修复
