### ISSUE TITLE
组件在小程序使用异常

### ISSUE THREAD

**Issue by sweetwisdom** [yang1206/uniapp-nutui#4]
使用uni_modules导入，组件在小程序使用异常，在H5显示正常

`

 Component is not found in path "uni_modules/nutui-uni/components/nutui-uni/components/popup/popup" (using by "uni_modules/nutui-uni/components/nutui-uni/components/menuitem/menuitem")(env: Windows,mp,1.06.2306281; lib: 2.33.0)

`

![image](https://github.com/yang1206/uniapp-nutui/assets/57869305/59be19c0-d011-4a36-a997-fa646a4ea097)

**Comment by yang1206** [comment]
#2 参考这个，不建议使用uni_modules
