### ISSUE TITLE
类型提示生效

### ISSUE THREAD

**Issue by Ttou** [yang1206/uniapp-nutui#5]
### 引用类型文件后，组件提示为 `any`

<img width="863" alt="image" src="https://github.com/yang1206/uniapp-nutui/assets/4298437/9931f9be-347b-44e2-bc6c-c15f1a67921a">

<img width="742" alt="image" src="https://github.com/yang1206/uniapp-nutui/assets/4298437/885fa2f1-2ad6-4cf2-9557-62b50067a130">

### 给组件设置类名，小程序下无法生效，h5正常

<img width="567" alt="image" src="https://github.com/yang1206/uniapp-nutui/assets/4298437/10c5eab3-51d6-45a2-af10-68623ebf5c12">

<img width="1238" alt="image" src="https://github.com/yang1206/uniapp-nutui/assets/4298437/534ef910-c471-4a05-a6df-47242775f0d8">

项目地址：https://gitee.com/jh_shot/uni-template

**Comment by yang1206** [comment]
https://github.com/vuejs/language-tools/issues/3388
请暂时将 volar 降级到 1.8以下，最新版

**Comment by Ttou** [comment]
类名通过 `custom-class` 和 `:deep()` 解决了，类型提示就在等等吧

**Comment by yang1206** [comment]
> 类名通过 `custom-class` 和 `:deep()` 解决了，类型提示就在等等吧

这个文档中写过了，uniapp 编译小程序不支持 class 和 style，请使用 custom-class 和 custom-style

**Comment by Ttou** [comment]
嗯，看到了

**Comment by Ttou** [comment]
@yang1206 volar 1.8.8 已经能正常推导组件类型了
