### ISSUE TITLE
小程序 demo 手写签名不可用

### ISSUE THREAD

**Issue by Lin-Ya** [yang1206/uniapp-nutui#7]
设备: iphone 12 iOS15.4.1
微信 v 8.0.33

故障：
滑动手写签名区域，没有反应。PS：按钮名字是否错了，应该是 “确认” 而非 “确实”

**Comment by yang1206** [comment]
签名目前仅支持 h5，文档中有标记，"确实"二字是用来演示自定义国际化文字
