### ISSUE TITLE
没有交流群吗？

### ISSUE THREAD

**Issue by travelCN** [yang1206/uniapp-nutui#8]
轮播不动啊。。不知道哪的问题。

https://github.com/yang1206/uniapp-nutui/assets/15223877/6f024ef6-55bc-4475-848b-7ff52866d5b0

**Comment by yang1206** [comment]
暂时没有交流群，请提供一个复现的示例，我这里测试没有问题

**Comment by travelCN** [comment]
就是官网的例子直接复制粘贴来的。基本没做修改。

**Comment by travelCN** [comment]
![image](https://github.com/yang1206/uniapp-nutui/assets/15223877/b639e570-34f6-4b83-907a-9127a38055e4)
![image](https://github.com/yang1206/uniapp-nutui/assets/15223877/494b6081-9b2b-439b-bd3e-de7bd7f43b35)

**Comment by yang1206** [comment]
是cli还是 hbuilder

**Comment by travelCN** [comment]
cli vite

**Comment by yang1206** [comment]
我在小程序和 h5 测试都没有问题，可以提供一个重现的工程吗

**Comment by travelCN** [comment]
关键是就是例子复制进去的。
`<template>
  <view>
    <nut-swiper init-page="1" width="100%" pagination-visible pagination-color="#426543">
      <nut-swiper-item>
        <img src="https://storage.360buyimg.com/jdc-article/NutUItaro34.jpg" alt="" />
      </nut-swiper-item>
      <nut-swiper-item>
        <img src="https://storage.360buyimg.com/jdc-article/NutUItaro2.jpg" alt="" />
      </nut-swiper-item>
      <nut-swiper-item>
        <img src="https://storage.360buyimg.com/jdc-article/welcomenutui.jpg" alt="" />
      </nut-swiper-item>
      <nut-swiper-item>
        <img src="https://storage.360buyimg.com/jdc-article/fristfabu.jpg" alt="" />
      </nut-swiper-item>
    </nut-swiper>
  </view>
</template>

<script setup>

</script>

<style lang="scss" scoped></style>`

**Comment by yang1206** [comment]
我无法重现这个问题，请新建一个项目重现这个问题

**Comment by travelCN** [comment]
代码就这些，啥玩意没有。小程序里就是问题的地方。清除过小程序的缓存。

**Comment by travelCN** [comment]
> 我无法重现这个问题，请新建一个项目重现这个问题

还要如何复现呢？就按照uniapp官网的vite cli新建个项目，然后按照咱们的ui npm 配置pages.json 然后使用个例子，就这样了

**Comment by yang1206** [comment]
我不知道你的环境不知道你的依赖，没办法调试啊，你这个问题在我这里没办法复现出来，最好的办法就是你给我一个能稳定复现这个问题的项目工程

**Comment by travelCN** [comment]
[wx-app.zip](https://github.com/yang1206/uniapp-nutui/files/12266494/wx-app.zip)

**Comment by travelCN** [comment]
> 我不知道你的环境不知道你的依赖，没办法调试啊，你这个问题在我这里没办法复现出来，最好的办法就是你给我一个能稳定复现这个问题的项目工程

稳不稳定我不清楚，这是我出现问题的工程文件。

**Comment by yang1206** [comment]
去掉 width="100%"

**Comment by travelCN** [comment]
这个位置不能100%？必须是一个确定的值？

**Comment by yang1206** [comment]
> 这个位置不能100%？必须是一个确定的值？

是，默认宽度就是撑满屏幕，如果想改就改父元素宽度或者图片宽度

**Comment by travelCN** [comment]
表示 width的默认window.innerWidth不生效，小程序里宽度不占满
:width='number' 也不生效。
![image](https://github.com/yang1206/uniapp-nutui/assets/15223877/9299f6cf-9717-4788-b4cc-a5c526abd045)

**Comment by yang1206** [comment]
https://github.com/yang1206/uniapp-nutui/blob/main/example/src/pages/demo/exhibition/swiper/index.vue

自行查看示例，这就是改个图片宽度而已

**Comment by travelCN** [comment]
你可以看那个工程里，把100%去掉是不是占用了小程序100%的宽度即可。
我这里清除缓存，总之是不变的。 设置宽度也无效。

**Comment by travelCN** [comment]
![image](https://github.com/yang1206/uniapp-nutui/assets/15223877/9b77b81a-553d-4c50-97d0-09eadbe9b15d)
代码用的同步，但是开发工具提示的是
![image](https://github.com/yang1206/uniapp-nutui/assets/15223877/51d02508-a3b0-4c4a-9cda-5fdc3c0f9564)

**Comment by yang1206** [comment]
你把img 标签宽度改成 100%就行了，另外 width只支持具体值是预期行为

**Comment by travelCN** [comment]
我只是说啊，咱们ui的例子上 直接复制粘贴是不是应该出现相应的效果。
但目前来说没有。也不可能每个人都会来github上看例子不是。
希望有用可能注明或修改。

**Comment by yang1206** [comment]
> 我只是说啊，咱们ui的例子上 直接复制粘贴是不是应该出现相应的效果。
> 
> 但目前来说没有。也不可能每个人都会来github上看例子不是。
> 
> 希望有用可能注明或修改。

你看文档啊，你本身就没复制粘贴完啊，文档上的示例img都是有样式的
